/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type ThreatCategory = {
    __kind__: "counterInsurgency";
    counterInsurgency: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "drugSmuggling";
    drugSmuggling: null;
} | {
    __kind__: "cyber";
    cyber: null;
} | {
    __kind__: "counterIntelligence";
    counterIntelligence: null;
} | {
    __kind__: "armsSmuggling";
    armsSmuggling: null;
} | {
    __kind__: "counterTerror";
    counterTerror: null;
} | {
    __kind__: "counterEspionage";
    counterEspionage: null;
} | {
    __kind__: "humanSmuggling";
    humanSmuggling: null;
};
export interface AssetProfile {
    bio: string;
    status: Variant_active_terminated_inactive;
    clearanceLevel: ClearanceLevel;
    createdBy: Principal;
    lastUpdate: Time;
    codename: string;
    specialization: Array<SpecializedSkill>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ClassifiedNote {
    title: string;
    body: string;
    createdBy: Principal;
    author: string;
    timestamp: Time;
    classification: ClearanceLevel;
}
export type SpecializedSkill = {
    __kind__: "counterInsurgency";
    counterInsurgency: null;
} | {
    __kind__: "humanIntelligence";
    humanIntelligence: null;
} | {
    __kind__: "militaryIntelligence";
    militaryIntelligence: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cyber";
    cyber: null;
} | {
    __kind__: "counterIntelligence";
    counterIntelligence: null;
} | {
    __kind__: "counterTerror";
    counterTerror: null;
} | {
    __kind__: "counterEspionage";
    counterEspionage: null;
} | {
    __kind__: "drugIntelligence";
    drugIntelligence: null;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BriefingObjective {
    text: string;
    priority: Variant_low_high_medium;
}
export interface ThreatAssessment {
    subjectName: string;
    createdBy: Principal;
    lastUpdate: Time;
    summary: string;
    threatCategory: ThreatCategory;
    linkedMissions: Array<string>;
    riskScore: bigint;
}
export interface HVTProfile {
    name: string;
    description: string;
    threatTier: ThreatLevel;
}
export interface MissionBriefing {
    exfilRoutes: string;
    classificationLevel: ClearanceLevel;
    leadOfficer: string;
    missionDate: Time;
    createdBy: Principal;
    lastUpdate: Time;
    hvtProfiles: Array<HVTProfile>;
    rulesOfEngagement: string;
    objectives: Array<BriefingObjective>;
    operationCodename: string;
}
export interface FieldReport {
    content: string;
    author: Principal;
    timestamp: Time;
}
export interface Mission {
    status: MissionStatus;
    isTemplate: boolean;
    threatLevel: ThreatLevel;
    missionType: MissionType;
    createdBy: Principal;
    lastUpdate: Time;
    assignedOperatives: Array<string>;
    codename: string;
    fieldReports: Array<FieldReport>;
    objectives: Array<string>;
}
export interface UserProfile {
    name: string;
    callsign: string;
    department: string;
}
export enum ClearanceLevel {
    topSecret = "topSecret",
    secret = "secret",
    TS_SCI = "TS_SCI",
    confidential = "confidential"
}
export enum MissionStatus {
    active = "active",
    aborted = "aborted",
    completed = "completed",
    compromised = "compromised"
}
export enum MissionType {
    cyber = "cyber",
    counterTerror = "counterTerror",
    inPersonOp = "inPersonOp",
    recon = "recon"
}
export enum ThreatLevel {
    low = "low",
    critical = "critical",
    elevated = "elevated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_terminated_inactive {
    active = "active",
    terminated = "terminated",
    inactive = "inactive"
}
export enum Variant_low_high_medium {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMissionFieldReport(codename: string, reportContent: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssetProfile(codename: string, clearanceLevel: ClearanceLevel, specialization: Array<SpecializedSkill>, status: Variant_active_terminated_inactive, bio: string): Promise<void>;
    createClassifiedNote(title: string, body: string, classification: ClearanceLevel, author: string): Promise<void>;
    createMission(codename: string, status: MissionStatus, threatLevel: ThreatLevel, assignedOperatives: Array<string>, missionType: MissionType, objectives: Array<string>): Promise<void>;
    createMissionBriefing(operationCodename: string, missionDate: Time, leadOfficer: string, objectives: Array<BriefingObjective>, hvtProfiles: Array<HVTProfile>, exfilRoutes: string, rulesOfEngagement: string, classificationLevel: ClearanceLevel): Promise<void>;
    createThreatAssessment(subjectName: string, threatCategory: ThreatCategory, riskScore: bigint, summary: string, linkedMissions: Array<string>): Promise<void>;
    deleteAssetProfile(codename: string): Promise<void>;
    deleteClassifiedNote(title: string): Promise<void>;
    deleteMission(codename: string): Promise<void>;
    deleteMissionBriefing(operationCodename: string): Promise<void>;
    deleteThreatAssessment(subjectName: string): Promise<void>;
    getAllAssetProfiles(): Promise<Array<AssetProfile>>;
    getAllClassifiedNotes(): Promise<Array<ClassifiedNote>>;
    getAllMissionBriefings(): Promise<Array<MissionBriefing>>;
    getAllMissions(): Promise<Array<Mission>>;
    getAllThreatAssessments(): Promise<Array<ThreatAssessment>>;
    getAssetProfile(codename: string): Promise<AssetProfile>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClassifiedNote(title: string): Promise<ClassifiedNote>;
    getCurrentTimestamp(): Promise<Time>;
    getMission(codename: string): Promise<Mission>;
    getMissionBriefing(operationCodename: string): Promise<MissionBriefing>;
    getMissionTemplates(): Promise<Array<Mission>>;
    getMissionsByStatus(status: MissionStatus): Promise<Array<Mission>>;
    getThreatAssessment(subjectName: string): Promise<ThreatAssessment>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMissionTemplate(codename: string, status: MissionStatus, threatLevel: ThreatLevel, assignedOperatives: Array<string>, missionType: MissionType, objectives: Array<string>): Promise<void>;
    updateAssetProfile(codename: string, clearanceLevel: ClearanceLevel, specialization: Array<SpecializedSkill>, status: Variant_active_terminated_inactive, bio: string): Promise<void>;
    updateClassifiedNote(title: string, body: string, classification: ClearanceLevel, author: string): Promise<void>;
    updateMission(codename: string, status: MissionStatus, threatLevel: ThreatLevel, assignedOperatives: Array<string>, missionType: MissionType, objectives: Array<string>): Promise<void>;
    updateMissionBriefing(operationCodename: string, missionDate: Time, leadOfficer: string, objectives: Array<BriefingObjective>, hvtProfiles: Array<HVTProfile>, exfilRoutes: string, rulesOfEngagement: string, classificationLevel: ClearanceLevel): Promise<void>;
    updateThreatAssessment(subjectName: string, threatCategory: ThreatCategory, riskScore: bigint, summary: string, linkedMissions: Array<string>): Promise<void>;
}
import type { AssetProfile as _AssetProfile, BriefingObjective as _BriefingObjective, ClassifiedNote as _ClassifiedNote, ClearanceLevel as _ClearanceLevel, FieldReport as _FieldReport, HVTProfile as _HVTProfile, Mission as _Mission, MissionBriefing as _MissionBriefing, MissionStatus as _MissionStatus, MissionType as _MissionType, SpecializedSkill as _SpecializedSkill, ThreatAssessment as _ThreatAssessment, ThreatCategory as _ThreatCategory, ThreatLevel as _ThreatLevel, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMissionFieldReport(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMissionFieldReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMissionFieldReport(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssetProfile(arg0: string, arg1: ClearanceLevel, arg2: Array<SpecializedSkill>, arg3: Variant_active_terminated_inactive, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssetProfile(arg0, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssetProfile(arg0, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createClassifiedNote(arg0: string, arg1: string, arg2: ClearanceLevel, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClassifiedNote(arg0, arg1, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClassifiedNote(arg0, arg1, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createMission(arg0: string, arg1: MissionStatus, arg2: ThreatLevel, arg3: Array<string>, arg4: MissionType, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMission(arg0, to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg1), to_candid_ThreatLevel_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MissionType_n20(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMission(arg0, to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg1), to_candid_ThreatLevel_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MissionType_n20(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createMissionBriefing(arg0: string, arg1: Time, arg2: string, arg3: Array<BriefingObjective>, arg4: Array<HVTProfile>, arg5: string, arg6: string, arg7: ClearanceLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMissionBriefing(arg0, arg1, arg2, to_candid_vec_n22(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n26(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMissionBriefing(arg0, arg1, arg2, to_candid_vec_n22(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n26(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async createThreatAssessment(arg0: string, arg1: ThreatCategory, arg2: bigint, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createThreatAssessment(arg0, to_candid_ThreatCategory_n29(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createThreatAssessment(arg0, to_candid_ThreatCategory_n29(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async deleteAssetProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssetProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssetProfile(arg0);
            return result;
        }
    }
    async deleteClassifiedNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClassifiedNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClassifiedNote(arg0);
            return result;
        }
    }
    async deleteMission(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMission(arg0);
            return result;
        }
    }
    async deleteMissionBriefing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMissionBriefing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMissionBriefing(arg0);
            return result;
        }
    }
    async deleteThreatAssessment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThreatAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThreatAssessment(arg0);
            return result;
        }
    }
    async getAllAssetProfiles(): Promise<Array<AssetProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssetProfiles();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssetProfiles();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClassifiedNotes(): Promise<Array<ClassifiedNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClassifiedNotes();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClassifiedNotes();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMissionBriefings(): Promise<Array<MissionBriefing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMissionBriefings();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMissionBriefings();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMissions(): Promise<Array<Mission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMissions();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMissions();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllThreatAssessments(): Promise<Array<ThreatAssessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllThreatAssessments();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllThreatAssessments();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetProfile(arg0: string): Promise<AssetProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetProfile(arg0);
                return from_candid_AssetProfile_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetProfile(arg0);
            return from_candid_AssetProfile_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassifiedNote(arg0: string): Promise<ClassifiedNote> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassifiedNote(arg0);
                return from_candid_ClassifiedNote_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassifiedNote(arg0);
            return from_candid_ClassifiedNote_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentTimestamp(): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTimestamp();
            return result;
        }
    }
    async getMission(arg0: string): Promise<Mission> {
        if (this.processError) {
            try {
                const result = await this.actor.getMission(arg0);
                return from_candid_Mission_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMission(arg0);
            return from_candid_Mission_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMissionBriefing(arg0: string): Promise<MissionBriefing> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissionBriefing(arg0);
                return from_candid_MissionBriefing_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissionBriefing(arg0);
            return from_candid_MissionBriefing_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMissionTemplates(): Promise<Array<Mission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissionTemplates();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissionTemplates();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMissionsByStatus(arg0: MissionStatus): Promise<Array<Mission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissionsByStatus(to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissionsByStatus(to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThreatAssessment(arg0: string): Promise<ThreatAssessment> {
        if (this.processError) {
            try {
                const result = await this.actor.getThreatAssessment(arg0);
                return from_candid_ThreatAssessment_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThreatAssessment(arg0);
            return from_candid_ThreatAssessment_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveMissionTemplate(arg0: string, arg1: MissionStatus, arg2: ThreatLevel, arg3: Array<string>, arg4: MissionType, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMissionTemplate(arg0, to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg1), to_candid_ThreatLevel_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MissionType_n20(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMissionTemplate(arg0, to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg1), to_candid_ThreatLevel_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MissionType_n20(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateAssetProfile(arg0: string, arg1: ClearanceLevel, arg2: Array<SpecializedSkill>, arg3: Variant_active_terminated_inactive, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssetProfile(arg0, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssetProfile(arg0, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateClassifiedNote(arg0: string, arg1: string, arg2: ClearanceLevel, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClassifiedNote(arg0, arg1, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClassifiedNote(arg0, arg1, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateMission(arg0: string, arg1: MissionStatus, arg2: ThreatLevel, arg3: Array<string>, arg4: MissionType, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMission(arg0, to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg1), to_candid_ThreatLevel_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MissionType_n20(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMission(arg0, to_candid_MissionStatus_n16(this._uploadFile, this._downloadFile, arg1), to_candid_ThreatLevel_n18(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MissionType_n20(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateMissionBriefing(arg0: string, arg1: Time, arg2: string, arg3: Array<BriefingObjective>, arg4: Array<HVTProfile>, arg5: string, arg6: string, arg7: ClearanceLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMissionBriefing(arg0, arg1, arg2, to_candid_vec_n22(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n26(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMissionBriefing(arg0, arg1, arg2, to_candid_vec_n22(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n26(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_ClearanceLevel_n10(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateThreatAssessment(arg0: string, arg1: ThreatCategory, arg2: bigint, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateThreatAssessment(arg0, to_candid_ThreatCategory_n29(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateThreatAssessment(arg0, to_candid_ThreatCategory_n29(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_AssetProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetProfile): AssetProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_BriefingObjective_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BriefingObjective): BriefingObjective {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_ClassifiedNote_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassifiedNote): ClassifiedNote {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ClearanceLevel_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClearanceLevel): ClearanceLevel {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_HVTProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HVTProfile): HVTProfile {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_MissionBriefing_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MissionBriefing): MissionBriefing {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_MissionStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MissionStatus): MissionStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_MissionType_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MissionType): MissionType {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Mission_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mission): Mission {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_SpecializedSkill_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpecializedSkill): SpecializedSkill {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatAssessment_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatAssessment): ThreatAssessment {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatCategory_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatCategory): ThreatCategory {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatLevel_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatLevel): ThreatLevel {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    status: {
        active: null;
    } | {
        terminated: null;
    } | {
        inactive: null;
    };
    clearanceLevel: _ClearanceLevel;
    createdBy: Principal;
    lastUpdate: _Time;
    codename: string;
    specialization: Array<_SpecializedSkill>;
}): {
    bio: string;
    status: Variant_active_terminated_inactive;
    clearanceLevel: ClearanceLevel;
    createdBy: Principal;
    lastUpdate: Time;
    codename: string;
    specialization: Array<SpecializedSkill>;
} {
    return {
        bio: value.bio,
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        clearanceLevel: from_candid_ClearanceLevel_n35(_uploadFile, _downloadFile, value.clearanceLevel),
        createdBy: value.createdBy,
        lastUpdate: value.lastUpdate,
        codename: value.codename,
        specialization: from_candid_vec_n37(_uploadFile, _downloadFile, value.specialization)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    body: string;
    createdBy: Principal;
    author: string;
    timestamp: _Time;
    classification: _ClearanceLevel;
}): {
    title: string;
    body: string;
    createdBy: Principal;
    author: string;
    timestamp: Time;
    classification: ClearanceLevel;
} {
    return {
        title: value.title,
        body: value.body,
        createdBy: value.createdBy,
        author: value.author,
        timestamp: value.timestamp,
        classification: from_candid_ClearanceLevel_n35(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exfilRoutes: string;
    classificationLevel: _ClearanceLevel;
    leadOfficer: string;
    missionDate: _Time;
    createdBy: Principal;
    lastUpdate: _Time;
    hvtProfiles: Array<_HVTProfile>;
    rulesOfEngagement: string;
    objectives: Array<_BriefingObjective>;
    operationCodename: string;
}): {
    exfilRoutes: string;
    classificationLevel: ClearanceLevel;
    leadOfficer: string;
    missionDate: Time;
    createdBy: Principal;
    lastUpdate: Time;
    hvtProfiles: Array<HVTProfile>;
    rulesOfEngagement: string;
    objectives: Array<BriefingObjective>;
    operationCodename: string;
} {
    return {
        exfilRoutes: value.exfilRoutes,
        classificationLevel: from_candid_ClearanceLevel_n35(_uploadFile, _downloadFile, value.classificationLevel),
        leadOfficer: value.leadOfficer,
        missionDate: value.missionDate,
        createdBy: value.createdBy,
        lastUpdate: value.lastUpdate,
        hvtProfiles: from_candid_vec_n46(_uploadFile, _downloadFile, value.hvtProfiles),
        rulesOfEngagement: value.rulesOfEngagement,
        objectives: from_candid_vec_n51(_uploadFile, _downloadFile, value.objectives),
        operationCodename: value.operationCodename
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    threatTier: _ThreatLevel;
}): {
    name: string;
    description: string;
    threatTier: ThreatLevel;
} {
    return {
        name: value.name,
        description: value.description,
        threatTier: from_candid_ThreatLevel_n49(_uploadFile, _downloadFile, value.threatTier)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    priority: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
}): {
    text: string;
    priority: Variant_low_high_medium;
} {
    return {
        text: value.text,
        priority: from_candid_variant_n54(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _MissionStatus;
    isTemplate: boolean;
    threatLevel: _ThreatLevel;
    missionType: _MissionType;
    createdBy: Principal;
    lastUpdate: _Time;
    assignedOperatives: Array<string>;
    codename: string;
    fieldReports: Array<_FieldReport>;
    objectives: Array<string>;
}): {
    status: MissionStatus;
    isTemplate: boolean;
    threatLevel: ThreatLevel;
    missionType: MissionType;
    createdBy: Principal;
    lastUpdate: Time;
    assignedOperatives: Array<string>;
    codename: string;
    fieldReports: Array<FieldReport>;
    objectives: Array<string>;
} {
    return {
        status: from_candid_MissionStatus_n58(_uploadFile, _downloadFile, value.status),
        isTemplate: value.isTemplate,
        threatLevel: from_candid_ThreatLevel_n49(_uploadFile, _downloadFile, value.threatLevel),
        missionType: from_candid_MissionType_n60(_uploadFile, _downloadFile, value.missionType),
        createdBy: value.createdBy,
        lastUpdate: value.lastUpdate,
        assignedOperatives: value.assignedOperatives,
        codename: value.codename,
        fieldReports: value.fieldReports,
        objectives: value.objectives
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjectName: string;
    createdBy: Principal;
    lastUpdate: _Time;
    summary: string;
    threatCategory: _ThreatCategory;
    linkedMissions: Array<string>;
    riskScore: bigint;
}): {
    subjectName: string;
    createdBy: Principal;
    lastUpdate: Time;
    summary: string;
    threatCategory: ThreatCategory;
    linkedMissions: Array<string>;
    riskScore: bigint;
} {
    return {
        subjectName: value.subjectName,
        createdBy: value.createdBy,
        lastUpdate: value.lastUpdate,
        summary: value.summary,
        threatCategory: from_candid_ThreatCategory_n65(_uploadFile, _downloadFile, value.threatCategory),
        linkedMissions: value.linkedMissions,
        riskScore: value.riskScore
    };
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    terminated: null;
} | {
    inactive: null;
}): Variant_active_terminated_inactive {
    return "active" in value ? Variant_active_terminated_inactive.active : "terminated" in value ? Variant_active_terminated_inactive.terminated : "inactive" in value ? Variant_active_terminated_inactive.inactive : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topSecret: null;
} | {
    secret: null;
} | {
    TS_SCI: null;
} | {
    confidential: null;
}): ClearanceLevel {
    return "topSecret" in value ? ClearanceLevel.topSecret : "secret" in value ? ClearanceLevel.secret : "TS_SCI" in value ? ClearanceLevel.TS_SCI : "confidential" in value ? ClearanceLevel.confidential : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    counterInsurgency: null;
} | {
    humanIntelligence: null;
} | {
    militaryIntelligence: null;
} | {
    other: string;
} | {
    cyber: null;
} | {
    counterIntelligence: null;
} | {
    counterTerror: null;
} | {
    counterEspionage: null;
} | {
    drugIntelligence: null;
}): {
    __kind__: "counterInsurgency";
    counterInsurgency: null;
} | {
    __kind__: "humanIntelligence";
    humanIntelligence: null;
} | {
    __kind__: "militaryIntelligence";
    militaryIntelligence: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cyber";
    cyber: null;
} | {
    __kind__: "counterIntelligence";
    counterIntelligence: null;
} | {
    __kind__: "counterTerror";
    counterTerror: null;
} | {
    __kind__: "counterEspionage";
    counterEspionage: null;
} | {
    __kind__: "drugIntelligence";
    drugIntelligence: null;
} {
    return "counterInsurgency" in value ? {
        __kind__: "counterInsurgency",
        counterInsurgency: value.counterInsurgency
    } : "humanIntelligence" in value ? {
        __kind__: "humanIntelligence",
        humanIntelligence: value.humanIntelligence
    } : "militaryIntelligence" in value ? {
        __kind__: "militaryIntelligence",
        militaryIntelligence: value.militaryIntelligence
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "cyber" in value ? {
        __kind__: "cyber",
        cyber: value.cyber
    } : "counterIntelligence" in value ? {
        __kind__: "counterIntelligence",
        counterIntelligence: value.counterIntelligence
    } : "counterTerror" in value ? {
        __kind__: "counterTerror",
        counterTerror: value.counterTerror
    } : "counterEspionage" in value ? {
        __kind__: "counterEspionage",
        counterEspionage: value.counterEspionage
    } : "drugIntelligence" in value ? {
        __kind__: "drugIntelligence",
        drugIntelligence: value.drugIntelligence
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    critical: null;
} | {
    elevated: null;
}): ThreatLevel {
    return "low" in value ? ThreatLevel.low : "critical" in value ? ThreatLevel.critical : "elevated" in value ? ThreatLevel.elevated : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Variant_low_high_medium {
    return "low" in value ? Variant_low_high_medium.low : "high" in value ? Variant_low_high_medium.high : "medium" in value ? Variant_low_high_medium.medium : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    aborted: null;
} | {
    completed: null;
} | {
    compromised: null;
}): MissionStatus {
    return "active" in value ? MissionStatus.active : "aborted" in value ? MissionStatus.aborted : "completed" in value ? MissionStatus.completed : "compromised" in value ? MissionStatus.compromised : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cyber: null;
} | {
    counterTerror: null;
} | {
    inPersonOp: null;
} | {
    recon: null;
}): MissionType {
    return "cyber" in value ? MissionType.cyber : "counterTerror" in value ? MissionType.counterTerror : "inPersonOp" in value ? MissionType.inPersonOp : "recon" in value ? MissionType.recon : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    counterInsurgency: null;
} | {
    other: string;
} | {
    drugSmuggling: null;
} | {
    cyber: null;
} | {
    counterIntelligence: null;
} | {
    armsSmuggling: null;
} | {
    counterTerror: null;
} | {
    counterEspionage: null;
} | {
    humanSmuggling: null;
}): {
    __kind__: "counterInsurgency";
    counterInsurgency: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "drugSmuggling";
    drugSmuggling: null;
} | {
    __kind__: "cyber";
    cyber: null;
} | {
    __kind__: "counterIntelligence";
    counterIntelligence: null;
} | {
    __kind__: "armsSmuggling";
    armsSmuggling: null;
} | {
    __kind__: "counterTerror";
    counterTerror: null;
} | {
    __kind__: "counterEspionage";
    counterEspionage: null;
} | {
    __kind__: "humanSmuggling";
    humanSmuggling: null;
} {
    return "counterInsurgency" in value ? {
        __kind__: "counterInsurgency",
        counterInsurgency: value.counterInsurgency
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "drugSmuggling" in value ? {
        __kind__: "drugSmuggling",
        drugSmuggling: value.drugSmuggling
    } : "cyber" in value ? {
        __kind__: "cyber",
        cyber: value.cyber
    } : "counterIntelligence" in value ? {
        __kind__: "counterIntelligence",
        counterIntelligence: value.counterIntelligence
    } : "armsSmuggling" in value ? {
        __kind__: "armsSmuggling",
        armsSmuggling: value.armsSmuggling
    } : "counterTerror" in value ? {
        __kind__: "counterTerror",
        counterTerror: value.counterTerror
    } : "counterEspionage" in value ? {
        __kind__: "counterEspionage",
        counterEspionage: value.counterEspionage
    } : "humanSmuggling" in value ? {
        __kind__: "humanSmuggling",
        humanSmuggling: value.humanSmuggling
    } : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetProfile>): Array<AssetProfile> {
    return value.map((x)=>from_candid_AssetProfile_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SpecializedSkill>): Array<SpecializedSkill> {
    return value.map((x)=>from_candid_SpecializedSkill_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassifiedNote>): Array<ClassifiedNote> {
    return value.map((x)=>from_candid_ClassifiedNote_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MissionBriefing>): Array<MissionBriefing> {
    return value.map((x)=>from_candid_MissionBriefing_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HVTProfile>): Array<HVTProfile> {
    return value.map((x)=>from_candid_HVTProfile_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BriefingObjective>): Array<BriefingObjective> {
    return value.map((x)=>from_candid_BriefingObjective_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Mission>): Array<Mission> {
    return value.map((x)=>from_candid_Mission_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ThreatAssessment>): Array<ThreatAssessment> {
    return value.map((x)=>from_candid_ThreatAssessment_n63(_uploadFile, _downloadFile, x));
}
function to_candid_BriefingObjective_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BriefingObjective): _BriefingObjective {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ClearanceLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClearanceLevel): _ClearanceLevel {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_HVTProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HVTProfile): _HVTProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_MissionStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionStatus): _MissionStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_MissionType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionType): _MissionType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_SpecializedSkill_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpecializedSkill): _SpecializedSkill {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ThreatCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatCategory): _ThreatCategory {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_ThreatLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatLevel): _ThreatLevel {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    priority: Variant_low_high_medium;
}): {
    text: string;
    priority: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
} {
    return {
        text: value.text,
        priority: to_candid_variant_n25(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    threatTier: ThreatLevel;
}): {
    name: string;
    description: string;
    threatTier: _ThreatLevel;
} {
    return {
        name: value.name,
        description: value.description,
        threatTier: to_candid_ThreatLevel_n18(_uploadFile, _downloadFile, value.threatTier)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClearanceLevel): {
    topSecret: null;
} | {
    secret: null;
} | {
    TS_SCI: null;
} | {
    confidential: null;
} {
    return value == ClearanceLevel.topSecret ? {
        topSecret: null
    } : value == ClearanceLevel.secret ? {
        secret: null
    } : value == ClearanceLevel.TS_SCI ? {
        TS_SCI: null
    } : value == ClearanceLevel.confidential ? {
        confidential: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "counterInsurgency";
    counterInsurgency: null;
} | {
    __kind__: "humanIntelligence";
    humanIntelligence: null;
} | {
    __kind__: "militaryIntelligence";
    militaryIntelligence: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cyber";
    cyber: null;
} | {
    __kind__: "counterIntelligence";
    counterIntelligence: null;
} | {
    __kind__: "counterTerror";
    counterTerror: null;
} | {
    __kind__: "counterEspionage";
    counterEspionage: null;
} | {
    __kind__: "drugIntelligence";
    drugIntelligence: null;
}): {
    counterInsurgency: null;
} | {
    humanIntelligence: null;
} | {
    militaryIntelligence: null;
} | {
    other: string;
} | {
    cyber: null;
} | {
    counterIntelligence: null;
} | {
    counterTerror: null;
} | {
    counterEspionage: null;
} | {
    drugIntelligence: null;
} {
    return value.__kind__ === "counterInsurgency" ? {
        counterInsurgency: value.counterInsurgency
    } : value.__kind__ === "humanIntelligence" ? {
        humanIntelligence: value.humanIntelligence
    } : value.__kind__ === "militaryIntelligence" ? {
        militaryIntelligence: value.militaryIntelligence
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "cyber" ? {
        cyber: value.cyber
    } : value.__kind__ === "counterIntelligence" ? {
        counterIntelligence: value.counterIntelligence
    } : value.__kind__ === "counterTerror" ? {
        counterTerror: value.counterTerror
    } : value.__kind__ === "counterEspionage" ? {
        counterEspionage: value.counterEspionage
    } : value.__kind__ === "drugIntelligence" ? {
        drugIntelligence: value.drugIntelligence
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_terminated_inactive): {
    active: null;
} | {
    terminated: null;
} | {
    inactive: null;
} {
    return value == Variant_active_terminated_inactive.active ? {
        active: null
    } : value == Variant_active_terminated_inactive.terminated ? {
        terminated: null
    } : value == Variant_active_terminated_inactive.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionStatus): {
    active: null;
} | {
    aborted: null;
} | {
    completed: null;
} | {
    compromised: null;
} {
    return value == MissionStatus.active ? {
        active: null
    } : value == MissionStatus.aborted ? {
        aborted: null
    } : value == MissionStatus.completed ? {
        completed: null
    } : value == MissionStatus.compromised ? {
        compromised: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatLevel): {
    low: null;
} | {
    critical: null;
} | {
    elevated: null;
} {
    return value == ThreatLevel.low ? {
        low: null
    } : value == ThreatLevel.critical ? {
        critical: null
    } : value == ThreatLevel.elevated ? {
        elevated: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionType): {
    cyber: null;
} | {
    counterTerror: null;
} | {
    inPersonOp: null;
} | {
    recon: null;
} {
    return value == MissionType.cyber ? {
        cyber: null
    } : value == MissionType.counterTerror ? {
        counterTerror: null
    } : value == MissionType.inPersonOp ? {
        inPersonOp: null
    } : value == MissionType.recon ? {
        recon: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_medium): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_medium.low ? {
        low: null
    } : value == Variant_low_high_medium.high ? {
        high: null
    } : value == Variant_low_high_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "counterInsurgency";
    counterInsurgency: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "drugSmuggling";
    drugSmuggling: null;
} | {
    __kind__: "cyber";
    cyber: null;
} | {
    __kind__: "counterIntelligence";
    counterIntelligence: null;
} | {
    __kind__: "armsSmuggling";
    armsSmuggling: null;
} | {
    __kind__: "counterTerror";
    counterTerror: null;
} | {
    __kind__: "counterEspionage";
    counterEspionage: null;
} | {
    __kind__: "humanSmuggling";
    humanSmuggling: null;
}): {
    counterInsurgency: null;
} | {
    other: string;
} | {
    drugSmuggling: null;
} | {
    cyber: null;
} | {
    counterIntelligence: null;
} | {
    armsSmuggling: null;
} | {
    counterTerror: null;
} | {
    counterEspionage: null;
} | {
    humanSmuggling: null;
} {
    return value.__kind__ === "counterInsurgency" ? {
        counterInsurgency: value.counterInsurgency
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "drugSmuggling" ? {
        drugSmuggling: value.drugSmuggling
    } : value.__kind__ === "cyber" ? {
        cyber: value.cyber
    } : value.__kind__ === "counterIntelligence" ? {
        counterIntelligence: value.counterIntelligence
    } : value.__kind__ === "armsSmuggling" ? {
        armsSmuggling: value.armsSmuggling
    } : value.__kind__ === "counterTerror" ? {
        counterTerror: value.counterTerror
    } : value.__kind__ === "counterEspionage" ? {
        counterEspionage: value.counterEspionage
    } : value.__kind__ === "humanSmuggling" ? {
        humanSmuggling: value.humanSmuggling
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SpecializedSkill>): Array<_SpecializedSkill> {
    return value.map((x)=>to_candid_SpecializedSkill_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BriefingObjective>): Array<_BriefingObjective> {
    return value.map((x)=>to_candid_BriefingObjective_n23(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HVTProfile>): Array<_HVTProfile> {
    return value.map((x)=>to_candid_HVTProfile_n27(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
