/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssetProfile {
  'bio' : string,
  'status' : { 'active' : null } |
    { 'terminated' : null } |
    { 'inactive' : null },
  'clearanceLevel' : ClearanceLevel,
  'createdBy' : Principal,
  'lastUpdate' : Time,
  'codename' : string,
  'specialization' : Array<SpecializedSkill>,
}
export interface BriefingObjective {
  'text' : string,
  'priority' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
}
export interface ClassifiedNote {
  'title' : string,
  'body' : string,
  'createdBy' : Principal,
  'author' : string,
  'timestamp' : Time,
  'classification' : ClearanceLevel,
}
export type ClearanceLevel = { 'topSecret' : null } |
  { 'secret' : null } |
  { 'TS_SCI' : null } |
  { 'confidential' : null };
export interface FieldReport {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface HVTProfile {
  'name' : string,
  'description' : string,
  'threatTier' : ThreatLevel,
}
export interface Mission {
  'status' : MissionStatus,
  'isTemplate' : boolean,
  'threatLevel' : ThreatLevel,
  'missionType' : MissionType,
  'createdBy' : Principal,
  'lastUpdate' : Time,
  'assignedOperatives' : Array<string>,
  'codename' : string,
  'fieldReports' : Array<FieldReport>,
  'objectives' : Array<string>,
}
export interface MissionBriefing {
  'exfilRoutes' : string,
  'classificationLevel' : ClearanceLevel,
  'leadOfficer' : string,
  'missionDate' : Time,
  'createdBy' : Principal,
  'lastUpdate' : Time,
  'hvtProfiles' : Array<HVTProfile>,
  'rulesOfEngagement' : string,
  'objectives' : Array<BriefingObjective>,
  'operationCodename' : string,
}
export type MissionStatus = { 'active' : null } |
  { 'aborted' : null } |
  { 'completed' : null } |
  { 'compromised' : null };
export type MissionType = { 'cyber' : null } |
  { 'counterTerror' : null } |
  { 'inPersonOp' : null } |
  { 'recon' : null };
export type SpecializedSkill = { 'counterInsurgency' : null } |
  { 'humanIntelligence' : null } |
  { 'militaryIntelligence' : null } |
  { 'other' : string } |
  { 'cyber' : null } |
  { 'counterIntelligence' : null } |
  { 'counterTerror' : null } |
  { 'counterEspionage' : null } |
  { 'drugIntelligence' : null };
export interface ThreatAssessment {
  'subjectName' : string,
  'createdBy' : Principal,
  'lastUpdate' : Time,
  'summary' : string,
  'threatCategory' : ThreatCategory,
  'linkedMissions' : Array<string>,
  'riskScore' : bigint,
}
export type ThreatCategory = { 'counterInsurgency' : null } |
  { 'other' : string } |
  { 'drugSmuggling' : null } |
  { 'cyber' : null } |
  { 'counterIntelligence' : null } |
  { 'armsSmuggling' : null } |
  { 'counterTerror' : null } |
  { 'counterEspionage' : null } |
  { 'humanSmuggling' : null };
export type ThreatLevel = { 'low' : null } |
  { 'critical' : null } |
  { 'elevated' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'callsign' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMissionFieldReport' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssetProfile' : ActorMethod<
    [
      string,
      ClearanceLevel,
      Array<SpecializedSkill>,
      { 'active' : null } |
        { 'terminated' : null } |
        { 'inactive' : null },
      string,
    ],
    undefined
  >,
  'createClassifiedNote' : ActorMethod<
    [string, string, ClearanceLevel, string],
    undefined
  >,
  'createMission' : ActorMethod<
    [
      string,
      MissionStatus,
      ThreatLevel,
      Array<string>,
      MissionType,
      Array<string>,
    ],
    undefined
  >,
  'createMissionBriefing' : ActorMethod<
    [
      string,
      Time,
      string,
      Array<BriefingObjective>,
      Array<HVTProfile>,
      string,
      string,
      ClearanceLevel,
    ],
    undefined
  >,
  'createThreatAssessment' : ActorMethod<
    [string, ThreatCategory, bigint, string, Array<string>],
    undefined
  >,
  'deleteAssetProfile' : ActorMethod<[string], undefined>,
  'deleteClassifiedNote' : ActorMethod<[string], undefined>,
  'deleteMission' : ActorMethod<[string], undefined>,
  'deleteMissionBriefing' : ActorMethod<[string], undefined>,
  'deleteThreatAssessment' : ActorMethod<[string], undefined>,
  'getAllAssetProfiles' : ActorMethod<[], Array<AssetProfile>>,
  'getAllClassifiedNotes' : ActorMethod<[], Array<ClassifiedNote>>,
  'getAllMissionBriefings' : ActorMethod<[], Array<MissionBriefing>>,
  'getAllMissions' : ActorMethod<[], Array<Mission>>,
  'getAllThreatAssessments' : ActorMethod<[], Array<ThreatAssessment>>,
  'getAssetProfile' : ActorMethod<[string], AssetProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassifiedNote' : ActorMethod<[string], ClassifiedNote>,
  'getCurrentTimestamp' : ActorMethod<[], Time>,
  'getMission' : ActorMethod<[string], Mission>,
  'getMissionBriefing' : ActorMethod<[string], MissionBriefing>,
  'getMissionTemplates' : ActorMethod<[], Array<Mission>>,
  'getMissionsByStatus' : ActorMethod<[MissionStatus], Array<Mission>>,
  'getThreatAssessment' : ActorMethod<[string], ThreatAssessment>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMissionTemplate' : ActorMethod<
    [
      string,
      MissionStatus,
      ThreatLevel,
      Array<string>,
      MissionType,
      Array<string>,
    ],
    undefined
  >,
  'updateAssetProfile' : ActorMethod<
    [
      string,
      ClearanceLevel,
      Array<SpecializedSkill>,
      { 'active' : null } |
        { 'terminated' : null } |
        { 'inactive' : null },
      string,
    ],
    undefined
  >,
  'updateClassifiedNote' : ActorMethod<
    [string, string, ClearanceLevel, string],
    undefined
  >,
  'updateMission' : ActorMethod<
    [
      string,
      MissionStatus,
      ThreatLevel,
      Array<string>,
      MissionType,
      Array<string>,
    ],
    undefined
  >,
  'updateMissionBriefing' : ActorMethod<
    [
      string,
      Time,
      string,
      Array<BriefingObjective>,
      Array<HVTProfile>,
      string,
      string,
      ClearanceLevel,
    ],
    undefined
  >,
  'updateThreatAssessment' : ActorMethod<
    [string, ThreatCategory, bigint, string, Array<string>],
    undefined
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];