/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClearanceLevel = IDL.Variant({
  'topSecret' : IDL.Null,
  'secret' : IDL.Null,
  'TS_SCI' : IDL.Null,
  'confidential' : IDL.Null,
});
export const SpecializedSkill = IDL.Variant({
  'counterInsurgency' : IDL.Null,
  'humanIntelligence' : IDL.Null,
  'militaryIntelligence' : IDL.Null,
  'other' : IDL.Text,
  'cyber' : IDL.Null,
  'counterIntelligence' : IDL.Null,
  'counterTerror' : IDL.Null,
  'counterEspionage' : IDL.Null,
  'drugIntelligence' : IDL.Null,
});
export const MissionStatus = IDL.Variant({
  'active' : IDL.Null,
  'aborted' : IDL.Null,
  'completed' : IDL.Null,
  'compromised' : IDL.Null,
});
export const ThreatLevel = IDL.Variant({
  'low' : IDL.Null,
  'critical' : IDL.Null,
  'elevated' : IDL.Null,
});
export const MissionType = IDL.Variant({
  'cyber' : IDL.Null,
  'counterTerror' : IDL.Null,
  'inPersonOp' : IDL.Null,
  'recon' : IDL.Null,
});
export const Time = IDL.Int;
export const BriefingObjective = IDL.Record({
  'text' : IDL.Text,
  'priority' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
});
export const HVTProfile = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'threatTier' : ThreatLevel,
});
export const ThreatCategory = IDL.Variant({
  'counterInsurgency' : IDL.Null,
  'other' : IDL.Text,
  'drugSmuggling' : IDL.Null,
  'cyber' : IDL.Null,
  'counterIntelligence' : IDL.Null,
  'armsSmuggling' : IDL.Null,
  'counterTerror' : IDL.Null,
  'counterEspionage' : IDL.Null,
  'humanSmuggling' : IDL.Null,
});
export const AssetProfile = IDL.Record({
  'bio' : IDL.Text,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'terminated' : IDL.Null,
    'inactive' : IDL.Null,
  }),
  'clearanceLevel' : ClearanceLevel,
  'createdBy' : IDL.Principal,
  'lastUpdate' : Time,
  'codename' : IDL.Text,
  'specialization' : IDL.Vec(SpecializedSkill),
});
export const ClassifiedNote = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdBy' : IDL.Principal,
  'author' : IDL.Text,
  'timestamp' : Time,
  'classification' : ClearanceLevel,
});
export const MissionBriefing = IDL.Record({
  'exfilRoutes' : IDL.Text,
  'classificationLevel' : ClearanceLevel,
  'leadOfficer' : IDL.Text,
  'missionDate' : Time,
  'createdBy' : IDL.Principal,
  'lastUpdate' : Time,
  'hvtProfiles' : IDL.Vec(HVTProfile),
  'rulesOfEngagement' : IDL.Text,
  'objectives' : IDL.Vec(BriefingObjective),
  'operationCodename' : IDL.Text,
});
export const FieldReport = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const Mission = IDL.Record({
  'status' : MissionStatus,
  'isTemplate' : IDL.Bool,
  'threatLevel' : ThreatLevel,
  'missionType' : MissionType,
  'createdBy' : IDL.Principal,
  'lastUpdate' : Time,
  'assignedOperatives' : IDL.Vec(IDL.Text),
  'codename' : IDL.Text,
  'fieldReports' : IDL.Vec(FieldReport),
  'objectives' : IDL.Vec(IDL.Text),
});
export const ThreatAssessment = IDL.Record({
  'subjectName' : IDL.Text,
  'createdBy' : IDL.Principal,
  'lastUpdate' : Time,
  'summary' : IDL.Text,
  'threatCategory' : ThreatCategory,
  'linkedMissions' : IDL.Vec(IDL.Text),
  'riskScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'callsign' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addMissionFieldReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssetProfile' : IDL.Func(
      [
        IDL.Text,
        ClearanceLevel,
        IDL.Vec(SpecializedSkill),
        IDL.Variant({
          'active' : IDL.Null,
          'terminated' : IDL.Null,
          'inactive' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createClassifiedNote' : IDL.Func(
      [IDL.Text, IDL.Text, ClearanceLevel, IDL.Text],
      [],
      [],
    ),
  'createMission' : IDL.Func(
      [
        IDL.Text,
        MissionStatus,
        ThreatLevel,
        IDL.Vec(IDL.Text),
        MissionType,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'createMissionBriefing' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Vec(BriefingObjective),
        IDL.Vec(HVTProfile),
        IDL.Text,
        IDL.Text,
        ClearanceLevel,
      ],
      [],
      [],
    ),
  'createThreatAssessment' : IDL.Func(
      [IDL.Text, ThreatCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteAssetProfile' : IDL.Func([IDL.Text], [], []),
  'deleteClassifiedNote' : IDL.Func([IDL.Text], [], []),
  'deleteMission' : IDL.Func([IDL.Text], [], []),
  'deleteMissionBriefing' : IDL.Func([IDL.Text], [], []),
  'deleteThreatAssessment' : IDL.Func([IDL.Text], [], []),
  'getAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllAssetProfiles' : IDL.Func([], [IDL.Vec(AssetProfile)], ['query']),
  'getAllClassifiedNotes' : IDL.Func([], [IDL.Vec(ClassifiedNote)], ['query']),
  'getAllMissionBriefings' : IDL.Func(
      [],
      [IDL.Vec(MissionBriefing)],
      ['query'],
    ),
  'getAllMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'getAllThreatAssessments' : IDL.Func(
      [],
      [IDL.Vec(ThreatAssessment)],
      ['query'],
    ),
  'getAssetProfile' : IDL.Func([IDL.Text], [AssetProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassifiedNote' : IDL.Func([IDL.Text], [ClassifiedNote], ['query']),
  'getCurrentTimestamp' : IDL.Func([], [Time], ['query']),
  'getMission' : IDL.Func([IDL.Text], [Mission], ['query']),
  'getMissionBriefing' : IDL.Func([IDL.Text], [MissionBriefing], ['query']),
  'getMissionTemplates' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'getMissionsByStatus' : IDL.Func(
      [MissionStatus],
      [IDL.Vec(Mission)],
      ['query'],
    ),
  'getThreatAssessment' : IDL.Func([IDL.Text], [ThreatAssessment], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMissionTemplate' : IDL.Func(
      [
        IDL.Text,
        MissionStatus,
        ThreatLevel,
        IDL.Vec(IDL.Text),
        MissionType,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateAssetProfile' : IDL.Func(
      [
        IDL.Text,
        ClearanceLevel,
        IDL.Vec(SpecializedSkill),
        IDL.Variant({
          'active' : IDL.Null,
          'terminated' : IDL.Null,
          'inactive' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateClassifiedNote' : IDL.Func(
      [IDL.Text, IDL.Text, ClearanceLevel, IDL.Text],
      [],
      [],
    ),
  'updateMission' : IDL.Func(
      [
        IDL.Text,
        MissionStatus,
        ThreatLevel,
        IDL.Vec(IDL.Text),
        MissionType,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateMissionBriefing' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Vec(BriefingObjective),
        IDL.Vec(HVTProfile),
        IDL.Text,
        IDL.Text,
        ClearanceLevel,
      ],
      [],
      [],
    ),
  'updateThreatAssessment' : IDL.Func(
      [IDL.Text, ThreatCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClearanceLevel = IDL.Variant({
    'topSecret' : IDL.Null,
    'secret' : IDL.Null,
    'TS_SCI' : IDL.Null,
    'confidential' : IDL.Null,
  });
  const SpecializedSkill = IDL.Variant({
    'counterInsurgency' : IDL.Null,
    'humanIntelligence' : IDL.Null,
    'militaryIntelligence' : IDL.Null,
    'other' : IDL.Text,
    'cyber' : IDL.Null,
    'counterIntelligence' : IDL.Null,
    'counterTerror' : IDL.Null,
    'counterEspionage' : IDL.Null,
    'drugIntelligence' : IDL.Null,
  });
  const MissionStatus = IDL.Variant({
    'active' : IDL.Null,
    'aborted' : IDL.Null,
    'completed' : IDL.Null,
    'compromised' : IDL.Null,
  });
  const ThreatLevel = IDL.Variant({
    'low' : IDL.Null,
    'critical' : IDL.Null,
    'elevated' : IDL.Null,
  });
  const MissionType = IDL.Variant({
    'cyber' : IDL.Null,
    'counterTerror' : IDL.Null,
    'inPersonOp' : IDL.Null,
    'recon' : IDL.Null,
  });
  const Time = IDL.Int;
  const BriefingObjective = IDL.Record({
    'text' : IDL.Text,
    'priority' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
  });
  const HVTProfile = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'threatTier' : ThreatLevel,
  });
  const ThreatCategory = IDL.Variant({
    'counterInsurgency' : IDL.Null,
    'other' : IDL.Text,
    'drugSmuggling' : IDL.Null,
    'cyber' : IDL.Null,
    'counterIntelligence' : IDL.Null,
    'armsSmuggling' : IDL.Null,
    'counterTerror' : IDL.Null,
    'counterEspionage' : IDL.Null,
    'humanSmuggling' : IDL.Null,
  });
  const AssetProfile = IDL.Record({
    'bio' : IDL.Text,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'terminated' : IDL.Null,
      'inactive' : IDL.Null,
    }),
    'clearanceLevel' : ClearanceLevel,
    'createdBy' : IDL.Principal,
    'lastUpdate' : Time,
    'codename' : IDL.Text,
    'specialization' : IDL.Vec(SpecializedSkill),
  });
  const ClassifiedNote = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdBy' : IDL.Principal,
    'author' : IDL.Text,
    'timestamp' : Time,
    'classification' : ClearanceLevel,
  });
  const MissionBriefing = IDL.Record({
    'exfilRoutes' : IDL.Text,
    'classificationLevel' : ClearanceLevel,
    'leadOfficer' : IDL.Text,
    'missionDate' : Time,
    'createdBy' : IDL.Principal,
    'lastUpdate' : Time,
    'hvtProfiles' : IDL.Vec(HVTProfile),
    'rulesOfEngagement' : IDL.Text,
    'objectives' : IDL.Vec(BriefingObjective),
    'operationCodename' : IDL.Text,
  });
  const FieldReport = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const Mission = IDL.Record({
    'status' : MissionStatus,
    'isTemplate' : IDL.Bool,
    'threatLevel' : ThreatLevel,
    'missionType' : MissionType,
    'createdBy' : IDL.Principal,
    'lastUpdate' : Time,
    'assignedOperatives' : IDL.Vec(IDL.Text),
    'codename' : IDL.Text,
    'fieldReports' : IDL.Vec(FieldReport),
    'objectives' : IDL.Vec(IDL.Text),
  });
  const ThreatAssessment = IDL.Record({
    'subjectName' : IDL.Text,
    'createdBy' : IDL.Principal,
    'lastUpdate' : Time,
    'summary' : IDL.Text,
    'threatCategory' : ThreatCategory,
    'linkedMissions' : IDL.Vec(IDL.Text),
    'riskScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'callsign' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addMissionFieldReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssetProfile' : IDL.Func(
        [
          IDL.Text,
          ClearanceLevel,
          IDL.Vec(SpecializedSkill),
          IDL.Variant({
            'active' : IDL.Null,
            'terminated' : IDL.Null,
            'inactive' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createClassifiedNote' : IDL.Func(
        [IDL.Text, IDL.Text, ClearanceLevel, IDL.Text],
        [],
        [],
      ),
    'createMission' : IDL.Func(
        [
          IDL.Text,
          MissionStatus,
          ThreatLevel,
          IDL.Vec(IDL.Text),
          MissionType,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'createMissionBriefing' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Vec(BriefingObjective),
          IDL.Vec(HVTProfile),
          IDL.Text,
          IDL.Text,
          ClearanceLevel,
        ],
        [],
        [],
      ),
    'createThreatAssessment' : IDL.Func(
        [IDL.Text, ThreatCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteAssetProfile' : IDL.Func([IDL.Text], [], []),
    'deleteClassifiedNote' : IDL.Func([IDL.Text], [], []),
    'deleteMission' : IDL.Func([IDL.Text], [], []),
    'deleteMissionBriefing' : IDL.Func([IDL.Text], [], []),
    'deleteThreatAssessment' : IDL.Func([IDL.Text], [], []),
    'getAdminList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllAssetProfiles' : IDL.Func([], [IDL.Vec(AssetProfile)], ['query']),
    'getAllClassifiedNotes' : IDL.Func(
        [],
        [IDL.Vec(ClassifiedNote)],
        ['query'],
      ),
    'getAllMissionBriefings' : IDL.Func(
        [],
        [IDL.Vec(MissionBriefing)],
        ['query'],
      ),
    'getAllMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'getAllThreatAssessments' : IDL.Func(
        [],
        [IDL.Vec(ThreatAssessment)],
        ['query'],
      ),
    'getAssetProfile' : IDL.Func([IDL.Text], [AssetProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassifiedNote' : IDL.Func([IDL.Text], [ClassifiedNote], ['query']),
    'getCurrentTimestamp' : IDL.Func([], [Time], ['query']),
    'getMission' : IDL.Func([IDL.Text], [Mission], ['query']),
    'getMissionBriefing' : IDL.Func([IDL.Text], [MissionBriefing], ['query']),
    'getMissionTemplates' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'getMissionsByStatus' : IDL.Func(
        [MissionStatus],
        [IDL.Vec(Mission)],
        ['query'],
      ),
    'getThreatAssessment' : IDL.Func([IDL.Text], [ThreatAssessment], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMissionTemplate' : IDL.Func(
        [
          IDL.Text,
          MissionStatus,
          ThreatLevel,
          IDL.Vec(IDL.Text),
          MissionType,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateAssetProfile' : IDL.Func(
        [
          IDL.Text,
          ClearanceLevel,
          IDL.Vec(SpecializedSkill),
          IDL.Variant({
            'active' : IDL.Null,
            'terminated' : IDL.Null,
            'inactive' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateClassifiedNote' : IDL.Func(
        [IDL.Text, IDL.Text, ClearanceLevel, IDL.Text],
        [],
        [],
      ),
    'updateMission' : IDL.Func(
        [
          IDL.Text,
          MissionStatus,
          ThreatLevel,
          IDL.Vec(IDL.Text),
          MissionType,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateMissionBriefing' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Vec(BriefingObjective),
          IDL.Vec(HVTProfile),
          IDL.Text,
          IDL.Text,
          ClearanceLevel,
        ],
        [],
        [],
      ),
    'updateThreatAssessment' : IDL.Func(
        [IDL.Text, ThreatCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };